#!/usr/bin/env python3
"""Generate manifest.yaml: a deterministic index of every template file with its
sha256. runbook-server verifies each downloaded file against this manifest before
writing it to the DB, so the sha256 here MUST be the sha256 of the raw file bytes
(identical formula to the syncer's decode step).

Usage:
  ./scripts/gen_manifest.py            # write manifest.yaml
  ./scripts/gen_manifest.py --check    # exit non-zero if manifest.yaml is stale
"""
import glob
import hashlib
import os
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_GLOB = os.path.join(ROOT, "templates", "*.yaml")
MANIFEST_PATH = os.path.join(ROOT, "manifest.yaml")


def build():
    entries = []
    for path in sorted(glob.glob(TEMPLATES_GLOB)):
        raw = open(path, "rb").read()
        doc = yaml.safe_load(raw)
        slug = doc.get("slug", "")
        stem = os.path.splitext(os.path.basename(path))[0]
        if slug != stem:
            raise SystemExit(f"{path}: slug {slug!r} does not match file name {stem!r}")
        entries.append(
            {
                "slug": slug,
                "path": "templates/" + os.path.basename(path),
                "sha256": hashlib.sha256(raw).hexdigest(),
            }
        )
    return entries


def render(entries):
    # Stable, minimal YAML so diffs are clean.
    lines = ["# Generated by scripts/gen_manifest.py — do not edit by hand.\n"]
    for e in entries:
        lines.append(f"- slug: {e['slug']}\n")
        lines.append(f"  path: {e['path']}\n")
        lines.append(f"  sha256: {e['sha256']}\n")
    return "".join(lines)


def main():
    rendered = render(build())
    if "--check" in sys.argv:
        current = open(MANIFEST_PATH).read() if os.path.exists(MANIFEST_PATH) else ""
        if current != rendered:
            print("manifest.yaml is stale; run scripts/gen_manifest.py and commit.", file=sys.stderr)
            sys.exit(1)
        print("manifest.yaml is up to date.")
        return
    with open(MANIFEST_PATH, "w") as f:
        f.write(rendered)
    print(f"wrote {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
